### ISSUE TITLE
微信无法修改定位

### ISSUE THREAD

**Issue by TiAmo-he** [ZCShou/GoGoGo#1]
为什么钉钉，美团都可以正常修改定位，但是微信不行，我想微信领个美团优惠券，结果没办法正常跳转

**Comment by ZCShou** [comment]
应该微信有这方面的检查

**Comment by 330132662** [comment]
https://github.com/user-attachments/assets/87fe917f-9193-4b6e-a960-2a12da8d81a9

**Comment by perfumescent** [comment]
> a48535427a3fecfb9d95229178caed75.mp4

你这啥意思，这个位置本来就不用定位

**Comment by 330132662** [comment]
本邮箱不作为工作生活用 请联系 ***@***.***
