### ISSUE TITLE
[BUG] 点击修改定位的时候，app闪退

### ISSUE THREAD

**Issue by superman3306** [ZCShou/GoGoGo#100]
### 缺陷描述 / Bug description

定位的时候闪退

### 版本信息 / Version Info

- 影梭版本 / GoGoGo Version : Go_1.11.3_arm64-v8a_release-signed
- 系统版本 / OS Version : 小米10pro、Android10、MIUI 11.0.12

### 复现步骤 / Steps to Reproduce

1. 正常打开app，赋予所有权限，此时都正常
2. 选中一个地方，然后点修改位置的按钮，闪退

**Comment by yzj2019** [comment]
看到一个说法，在开app之前关掉wifi，可能会有帮助
