### ISSUE TITLE
[BUG] New BUG

### ISSUE THREAD

**Issue by turr6** [ZCShou/GoGoGo#102]
### 缺陷描述 / Bug description
小米5【安卓8】安裝應用出現 解析錯誤

### 版本信息 / Version Info

- 影梭版本 / GoGoGo Version : 1.11.3
- 系统版本 / OS Version : 安卓8【miui10.2|穩定版 10.2.1.0[oaacnxm] 】

### 复现步骤 / Steps to Reproduce

1. 從github上下載apk,安裝，然後出現 安裝包解析錯誤
2.

**Comment by ZCShou** [comment]
现在要求最低 Android 8.1 版本
