### ISSUE TITLE
[Question] 1.12.1版本改包名重签以后无法自动定位，但是旧版的没问题

### ISSUE THREAD

**Issue by MissThee** [ZCShou/GoGoGo#112]
### 问题描述 / Problem Description

因为有些app会检测其他应用包名，需要将影梭重签改包名，之前1.11.2重签完，安装可以正常使用。
1.12.1版本重签名之后，影梭就不能获取当前定位了，已经授予了定位权限，也总是定位到海里的一个地方。

### 版本信息 / Version Info

- 影梭版本 / GoGoGo Version : 1.12.1
- 系统版本 / OS Version :  原生安卓14

**Comment by ZCShou** [comment]
这个取决于 百度地图 SDK。百度地图 SDK 是要求包名的，按理说改了就应该不能用，不知道为啥旧版本能用！
