### ISSUE TITLE
从某地看到一个需要手机号的版本

### ISSUE THREAD

**Issue by 3272539883** [ZCShou/GoGoGo#117]
![Screenshot_2024-06-05-17-13-39-866_com huati](https://github.com/ZCShou/GoGoGo/assets/72239269/a349bfec-643e-4fa1-9d4f-b75198a5d9c7)
![Screenshot_2024-06-05-17-13-54-889_com rocot yss](https://github.com/ZCShou/GoGoGo/assets/72239269/056015f9-142f-4243-9b97-011c66dc138a)
![Screenshot_2024-06-05-17-14-01-569_bin mt plus](https://github.com/ZCShou/GoGoGo/assets/72239269/09f3332c-a998-4657-88f2-15f6bbdfdebb)

**Comment by ZCShou** [comment]
感谢反馈，目前影梭已经没很多网友白嫖去收费了！
