### ISSUE TITLE
[Question] Help

### ISSUE THREAD

**Issue by laniceofficial** [ZCShou/GoGoGo#129]
### 问题描述 / Problem Description

我想问下为什么需要电话本和视频的权限？

### 版本信息 / Version Info

- 影梭版本 / GoGoGo Version : 1.12.1
- 系统版本 / OS Version :

**Comment by ZCShou** [comment]
1. 获取通话状态的权限是用来实现注册功能的，不过该功能目前并没有完成
    > 注意，获取通话状态并不能读取通讯录，通话记录，只能获取到自己的手机号（不过，很多品牌手机不提供，因而获取到的也是空的）
2. 访问设备上的照片、视频、音频是因为影梭存储历史记录和 LOG 的功能（通过文件管理器就可以在存储卡中找到这两个存储文件），而申请存储权限用户看到的提示就是 “访问设备上的照片、视频、音频”
3. 影梭全部代码已经开源，还有不明白的具体参见源代码以及 Google 官方的权限说明即可。实在不放心使用预编译的 APK，自己下载源码编译即可！

**Comment by laniceofficial** [comment]
好的，因为自己也是一个小白不是很懂这个😿谢谢了
