### ISSUE TITLE
[Feature] New function:加入其他提供商的地图，如Bing或Google

### ISSUE THREAD

**Issue by c2xvi** [ZCShou/GoGoGo#13]
### 描述 / Description

如题，目前该项目中只能使用百度地图，因此无法较好地使用外国位置的虚拟定位，请问maintainer有考虑过添加其他的地图供应商吗？

### 必要性 / Necessity

对于国外/港澳台地区的用户较为方便。

### 实现方法 / How to accomplish

直接引入Bing/Google的API即可？

**Comment by ZCShou** [comment]
与 #14 重复
