### ISSUE TITLE
[Question] Help，请问开了虚拟定位功能之后，高德地图的定位变化了，小红书/抖音的定位还是不变的，怎么办？

### ISSUE THREAD

**Issue by xiaoaxe** [ZCShou/GoGoGo#138]
### 版本信息 / Version Info

- 影梭版本 / GoGoGo Version : 
- 系统版本 / OS Version :

**Comment by ZCShou** [comment]
小红书/抖音，微信等都有对虚拟定位的检测，建议联系他们的开发团队，让他们取消虚拟定位检测即可！

**Comment by kof8855** [comment]
高德地图能用吗？我的意思是高德用了之后，足迹会记录进去吗？我想定位到每个省，让我的账号足迹点亮全国
