### ISSUE TITLE
[Question] Help 模拟定位时终止进程后会影响真实定位吗

### ISSUE THREAD

**Issue by nightgpt** [ZCShou/GoGoGo#139]
### 问题描述 / Problem Description
很愚蠢的问题捏

会不会这样终止后就改不回来 一直停留在模拟位置那种情况
(对于这方面一点也不懂 求解答 谢谢)

### 版本信息 / Version Info

- 影梭版本 / GoGoGo Version : 
- 系统版本 / OS Version :

**Comment by nightgpt** [comment]
不是正常终止模拟定位 而是在后台划进程

**Comment by ZCShou** [comment]
如果出现这样的问题唯一的可能就是Android系统有非常严重的BUG！试想一下，进程都能被结束了，还能起作用，如果真有这种问题，各种病毒程序不就可以神一般的存在，用户完全不知道其存在了！

**Comment by nightgpt** [comment]
嗯 所以才说挺愚蠢的

**Comment by nightgpt** [comment]
.

**Comment by nightgpt** [comment]
所以才说挺愚蠢

**Comment by nightgpt** [comment]
所以才说挺愚蠢
