### ISSUE TITLE
[Question] 鸿蒙系统打卡问题

### ISSUE THREAD

**Issue by Appeal-specific** [ZCShou/GoGoGo#157]
### 问题描述 / Problem Description
打开鸿蒙开发者模式，运行影梭 提示定位功能不可能

### 版本信息 / Version Info
- 影梭版本 / GoGoGo Version :  1.12.1
- 系统版本 / OS Version : 鸿蒙 4.0版本

**Comment by zzti** [comment]
我的也是，提示定位功能不可用

**Comment by zzti** [comment]
![Screenshot_20241003_085602_com zcshou gogogo](https://github.com/user-attachments/assets/b201bb11-70e0-4f85-980a-13651e7ce62c)
