### ISSUE TITLE
[Feature] 使用滴滴车主APP无法进行定位

### ISSUE THREAD

**Issue by chivaszhu** [ZCShou/GoGoGo#169]
### 描述 / Description
使用滴滴车主APP无法进行定位，已经关闭了wifi和蓝牙，还有什么文档可以参考吗

**Comment by mowenyude** [comment]
用微信骑，青桔的共享单车。他会获取微信的位置使用，为什么有时候好使，有时候不好使？怎么解决呀？它主要就是获取微信的位置信息来使用的
