### ISSUE TITLE
[Question] 虚拟定位对腾讯地图无效？

### ISSUE THREAD

**Issue by ljfrankie** [ZCShou/GoGoGo#171]
### 问题描述 / Problem Description
hi，我已经关掉蓝牙和Wifi，百度地图和高德地图可以虚拟定位，腾讯地图不可以？

### 版本信息 / Version Info

- 影梭版本 / GoGoGo Version : 1.12.1
- 系统版本 / OS Version : Android 14 / Xiaomi HyperOS 1.0.13

**Comment by uatdark** [comment]
+1，腾讯系地图不生效
