### ISSUE TITLE
[Help] 企业微信打卡定位100%成功方法！

### ISSUE THREAD

**Issue by death4444** [ZCShou/GoGoGo#175]
### 问题描述 / Problem Description
企业微信打卡定位100%成功，家人们，我已经测试出来了
简单流程及关键操作如下：
1.开启影梭并选好目标位置，开启模拟定位，出现浮窗
![image](https://github.com/user-attachments/assets/c0220910-d1d8-45fb-8fd7-edd9f9ad5e81)

2.去开发者模式里面把影梭设置为模拟定位的应用，并屏蔽企业微信读取其他应用的权限
![image](https://github.com/user-attachments/assets/82023334-d6d9-49aa-81d2-84ef4b498a3e)
![image](https://github.com/user-attachments/assets/174efe57-6b45-4fb1-99fb-dfaedb2633f0)

3.打开企微，进入打卡界面，提示不在打卡范围，不要管它
![image](https://github.com/user-attachments/assets/a87ed142-bfb2-4b0d-9bc7-6bb5d36c5d2f)

4.使用影梭的浮窗，再次设置目标位置
![image](https://github.com/user-attachments/assets/9fd1a973-3ebd-4263-9319-b50c4963edd6)

5.立刻断网，动作要快，目的是不让企微通过网络获取位置，从而保证我们设置的位置不会被覆盖（屏蔽基站定位）
![image](https://github.com/user-attachments/assets/738b291d-bd39-4f55-8a72-dcc59f40bc9e)

6.点这里进去，然后退回来，目的是刷新企微从android系统获取到的定位数据
只有这一个方法可以，点其他地方都不行
![image](https://github.com/user-attachments/assets/a4e853ca-ea34-46f0-ab52-b48546d58216)
![image](https://github.com/user-attachments/assets/8224ff48-cb7b-4ea0-8822-266573f96c9f)
点这些地方都不行

7.等几秒钟，等提示消失
![image](https://github.com/user-attachments/assets/a92f75db-21ff-41b9-a887-bd59e8cf29ae)
![image](https://github.com/user-attachments/assets/f1db3469-8771-4ca7-a80c-4d5337ded477)

8.联网
![image](https://github.com/user-attachments/assets/901fb250-1f9a-4eb1-b174-2b49e8c250dd)

9.立刻打卡，动作要快，否则企微又会通过基站定位，覆盖我们设置的位置
![image](https://github.com/user-attachments/assets/1b17f626-2600-4617-b32c-d932960c4477)
![image](https://github.com/user-attachments/assets/8cb79375-d390-48a5-bd03-de45faf66206)

10.成功，并且没有异常风险提示
![image](https://github.com/user-attachments/assets/c0ba8988-d0f6-4eb0-9a41-0bcd08ad6f87)

### 版本信息 / Version Info

- 影梭版本 / GoGoGo Version : v1.12.1
- 系统版本 / OS Version : miui（非澎湃）14.0.4；企业微信4.1.30
![Screenshot_2024-10-22-12-13-19-800_com android settings](https://github.com/user-attachments/assets/63392536-7657-4d21-9d4d-b6de44e2de20)
![Screenshot_2024-10-22-12-15-34-139_com android settings](https://github.com/user-attachments/assets/a980f675-2cb6-4d5c-92e6-151209ac7b20)

**Comment by liruibingniubi** [comment]
碉堡了

**Comment by liudih** [comment]
今晚试试

**Comment by Matcha2333** [comment]
拍照打卡如何解决

**Comment by saintxu777** [comment]
无敌，真的有效，荣耀magic v2，企业微信4.1.30版本，20250206亲测，感谢分享！！111

**Comment by luoxiangxl** [comment]
您发给我的信件已经收到。

**Comment by a81n9** [comment]
Redmi K30 Pro 亲测可以

**Comment by syswcq** [comment]
退订TD

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年2月12日(周三) 中午12:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [ZCShou/GoGoGo] [Help] 企业微信打卡定位100%成功方法！ (Issue #175)




 
Redmi K30 Pro 亲测可以

**Comment by luoxiangxl** [comment]
您发给我的信件已经收到。

**Comment by GGforceP** [comment]
牛逼，2025.3.16，20:32实测有效

**Comment by luoxiangxl** [comment]
您发给我的信件已经收到。

**Comment by applechi** [comment]
牛逼plus，2025.04.18，还是可以！！！

**Comment by luoxiangxl** [comment]
您发给我的信件已经收到。

**Comment by iamdeemo** [comment]
2025.4.26 红米K80P 实测成功

**Comment by sunlho** [comment]
太棒了，救命稻草

**Comment by singleSheep** [comment]
好像不行了,现在断网进入打卡界面会出现一个网络错误的对话框,点击确定以后直接退出上一个界面

**Comment by luoxiangxl** [comment]
您发给我的信件已经收到。

**Comment by zhuchaojiebao** [comment]
必须给你点赞！虽说一开始没有领会部分步奏，在尝试5遍后终于找到窍门！

**Comment by ILYSHL** [comment]
2025.08.15正常使用

**Comment by Boyka9527** [comment]
有人遇到这种嘛？最后的打卡地点显示未命名企业，然后位置为null<img width="320" height="357" alt="Image" src="https://github.com/user-attachments/assets/6853af7c-2591-47bd-95a9-31d240b24391" />

**Comment by Gavin-2023** [comment]
5.0版本的企微测试失败，估计是把漏洞补上了

**Comment by zhuchaojiebao** [comment]
可以的！你仔细看下哪里出了问题！我今天还打卡！

**Comment by khchr99wnn-arch** [comment]
牛的。有用，谢谢分享

**Comment by luoxiangxl** [comment]
您发给我的信件已经收到。

**Comment by death4444** [comment]
时至今日，一直有效，兄弟们冲。
只要版本不更新，就应该一直有效，直到企业微信4.1.30版本无法登录为止！
但愿企微团队做点人事，都是牛马，不要互相为难

**Comment by luoxiangxl** [comment]
您发给我的信件已经收到。

**Comment by GGforceP** [comment]
> 时至今日，一直有效，兄弟们冲。 只要版本不更新，就应该一直有效，直到企业微信4.1.30版本无法登录为止！ 但愿企微团队做点人事，都是牛马，不要互相为难

实测，即便是最新的5.0也可以用

**Comment by Ayahane** [comment]
昨天看了好多什么虚拟机、定位软件，乱七八糟的还有收费定制，最后让我刷到这个issue，今天试了试，还真可以，5.0版本也没问题。重连移动网络的那一瞬间打卡，就成功了。感觉已经无敌了，在家就打卡上了。感谢分享，全网最有用的一集。

**Comment by luoxiangxl** [comment]
您发给我的信件已经收到。

**Comment by qq182692678-netizen** [comment]
用这个方法已经一段时间了，打卡拍照都没有问题，这个方法真是碉堡了，之前只能用旧版，现在新版也可以了

**Comment by BearQu** [comment]
今天这个方法依旧可用，关闭 5G 网络，或者在电梯、地下室等网络情况不佳的地段成功率几乎 100%

**Comment by Y1rennnnnn** [comment]
> 牛的。有用，谢谢分享

还能用吗

**Comment by 1998cyy** [comment]
> > 牛的。有用，谢谢分享
> 
> 还能用吗

可以用，基本百分百

**Comment by Ashitaka-Sutra** [comment]
发现用这个方法，企业微信会多次读取位置信息，这个管理员在后台能看见吗？

**Comment by joserphlin** [comment]
厉害了，澎湃OS 3 依然可以用

**Comment by lvtao65535** [comment]
其他软件也可以效仿，本质上就是快速操作以绕过联网的定位

**Comment by Zillzhou** [comment]
外出打卡显示的只有经纬度

**Comment by 123wjr** [comment]
我去，微信照搬成功！感谢分享，狠狠follow

**Comment by devilmandare** [comment]
企业微信4.1.26测试成功，感谢分享

**Comment by YinXiqing** [comment]
牛逼，可用

**Comment by Fugeg** [comment]
2026 7 6仍然可用！

**Comment by JonathanZhang981** [comment]
> 2026 7 6仍然可用！
哈哈哈，我也用上了

**Comment by deboerda** [comment]
牛哇牛蛙

**Comment by kame99911** [comment]
Samsumg手机没找到拒绝读取应用列表的设定
有解吗？

**Comment by superealboom** [comment]
牛的，现在依然有用

**Comment by wenxiLubia** [comment]
> 牛的，现在依然有用

怎么用啊， 我怎么照着操作都不行啊

**Comment by superealboom** [comment]
> > 牛的，现在依然有用
> 
> 怎么用啊， 我怎么照着操作都不行啊

就是按照教程来的，你仔细再试试
