### ISSUE TITLE
[Feature] 添加 ADB 定位控制功能

### ISSUE THREAD

**Issue by MSCMonster** [ZCShou/GoGoGo#176]
### 描述 / Description

希望添加一个通过 ADB 命令直接控制位置更新的功能，以便在自动化测试或开发过程中，可以直接使用脚本设置位置而不需要手动操作应用界面。

### 必要性 / Necessity

在开发和测试过程中，能够通过 ADB 命令控制位置可以大幅提高效率，避免每次都需要手动操作应用，从而节省时间和精力。
（也方便编写在keep上跑一个miku之类的功能代码）

**Comment by e790a8** [comment]
请问这个功能有支持吗？
