### ISSUE TITLE
[BUG] New BUG: 没有打开地址位置开关, 却提示"搜索失败, 检查网络连接"

### ISSUE THREAD

**Issue by hsiong** [ZCShou/GoGoGo#22]
### 缺陷描述 / Bug description
在关闭地址位置开关的情况下, 使用本软件进行地理位置搜索, 提示"搜索失败, 检查网络连接"

### 版本信息 / Version Info

- 影梭版本 / GoGoGo Version : V1.10.1
- 系统版本 / OS Version : MIUI 13.0.5 (android 12)

### 复现步骤 / Steps to Reproduce

1. 关闭地理位置开关, 搜索城市, 提示"搜索失败, 检查网络连接"
![image](https://user-images.githubusercontent.com/37357447/191656463-7329c68b-d901-470d-98cd-c4c5c5c5df3e.png)
![image](https://user-images.githubusercontent.com/37357447/191656503-b31c5c12-52c9-43b7-9d88-f7de398270df.png)

2. 打开地理位置开关, 搜索城市, 功能正常; 说明提示出了 bug
![image](https://user-images.githubusercontent.com/37357447/191656545-5834e14c-7411-4404-a95c-acbef85c2a27.png)
![image](https://user-images.githubusercontent.com/37357447/191656604-9a0f9313-c1c5-405c-8cf7-fcbda3030045.png)

**Comment by hsiong** [comment]
ty  :D

**Comment by ZCShou** [comment]
这是由于关闭位置之后，百度地图的 API 将无法搜索到结果，直接抛出了异常。所有异常，我没有详细区分，都是提示“搜索失败, 检查网络连接”。

**Comment by ZCShou** [comment]
目前来看，也没啥好的解决方法。顶多改进一下提示！

**Comment by hsiong** [comment]
嗯   是的    个人认为改进一下提示就好了   原来的提示有点误导, 初次使用还是有点头痛的

**Comment by ZCShou** [comment]
已经更新了相关提示文本

**Comment by hsiong** [comment]
非常感谢！
