### ISSUE TITLE
[Question] Help

### ISSUE THREAD

**Issue by nonconformistqi** [ZCShou/GoGoGo#24]
### 问题描述 / Problem Description
为什么要通讯录和文件的访问权限

### 版本信息 / Version Info

- 影梭版本 / GoGoGo Version : 
- 系统版本 / OS Version :

**Comment by ZCShou** [comment]
没有请求通讯录权限，至于文件权限是因为需要记录 LOG
所有权限可以在 https://github.com/ZCShou/GoGoGo/blob/master/app/src/main/AndroidManifest.xml 查看
