### ISSUE TITLE
[BUG] New BUG

### ISSUE THREAD

**Issue by C315703603** [ZCShou/GoGoGo#25]
### 缺陷描述 / Bug description
应用闪退。
开启了悬浮窗和定位模拟后，选择定位时闪退

### 版本信息 / Version Info

- 影梭版本 / GoGoGo Version : 1.10.3
- 系统版本 / OS Version : MIUI12.0.11，android10

### 复现步骤 / Steps to Reproduce

1. 允许打开悬浮窗
2. 允许位置模拟
3. 移动到指定位置
4. 开启定位，闪退

**Comment by ZCShou** [comment]
主菜单有个问题反馈，里面有个 Log 记录，能否提供一下分析问题（注意屏蔽里面可能包含的个人信息）

**Comment by C315703603** [comment]
重启手机后解决了，不过微信定位还是真实的位置

**Comment by ZCShou** [comment]
> 重启手机后解决了，不过微信定位还是真实的位置

微信有相应检测，非 root 目前应该没有啥有效方法可以修改微信定位（也可能是我不知道）。
