### ISSUE TITLE
[Question] Help

### ISSUE THREAD

**Issue by ZORfree** [ZCShou/GoGoGo#28]
最新版本，MIUI12.5

开发者选项，选择位置信息应用，只有 无，影梭两个选项，

选中影梭后，显示模拟位置信息应用：美团

使用美团，确实位置被修改了，但是其他的app都没有被修改，想问一下 怎么应用于其他APP呢

**Comment by ZCShou** [comment]
其他 APP 是指啥？很多 APP（例如微信）有对应处理，非root 的 虚拟定位对它不生效
