### ISSUE TITLE
[BUG] 运动世界校园无法修改定位

### ISSUE THREAD

**Issue by MossCG** [ZCShou/GoGoGo#34]
### 缺陷描述 / Bug description

软件启动后 运动世界校园无法获取GPS定位
软件正常运行 高德地图里面也可以正常定位
WIFI蓝牙已关 只开流量 和 位置信息

### 版本信息 / Version Info

- 影梭版本 / GoGoGo Version : 1.11.1
- 系统版本 / OS Version : MIUI 13.0.3/Magic UI 4.0.0

### 复现步骤 / Steps to Reproduce

1. 运行运动世界校园，影梭正常启动并开启定位
2. 运动世界校园点击开始运动

**Comment by ZCShou** [comment]
软件有针对虚拟定位的检测，无解！

**Comment by MossCG** [comment]
> 软件有针对虚拟定位的检测，无解！

好的 感谢回复
