### ISSUE TITLE
[Feature] 关于摇杆的一些建议

### ISSUE THREAD

**Issue by MossCG** [ZCShou/GoGoGo#35]
### 描述 / Description
是否可以用户自行设置摇杆大小
（因为当屏幕较大或是手比较大的时候会有点不方便）

以及是否可以设置路径点，软件去自行移动（有点小懒2333）

### 必要性 / Necessity
建议，推荐调整

**Comment by ZCShou** [comment]
我是业余瞎搞的，android 不怎么会：
1. 动态调节大小不知道咋实现
2. 路径我正在边学习边搞

**Comment by ZCShou** [comment]
我将摇杆适当增大了一些，至于动态调节大小比较麻烦，目前代码比较烂
1. 摇杆上的按键都是固定大小，放大是所有按键都得改动
2. 摇杆按键的图标也需要动态放大
