### ISSUE TITLE
[BUG] 荣耀v30 点定位按钮闪退

### ISSUE THREAD

**Issue by MarvinXu** [ZCShou/GoGoGo#48]
### 缺陷描述 / Bug description
![image](https://user-images.githubusercontent.com/7382357/225963164-e530d671-d422-4734-bc91-21754a94c2fd.png)

点定位按钮闪退

### 版本信息 / Version Info

- 影梭版本 / GoGoGo Version : 1.11.1
- 系统版本 / OS Version : 鸿蒙os2.0

### 复现步骤 / Steps to Reproduce

1. 按要求开启权限和虚拟定位
2. 点击app中定位按钮

**Comment by ZCShou** [comment]
没有鸿蒙手机，无法验证！如方便菜单里有个问题反馈，把日志发出来看看。注意，如果，日志中有你认为的隐私信息，请注意屏蔽
