### ISSUE TITLE
[Feature] 事实上很多软件的定位采用了基站辅助，加入基站伪装才能真正实现虚拟定位

### ISSUE THREAD

**Issue by ikarosu** [ZCShou/GoGoGo#50]
### 描述 / Description
以前有个叫“模拟位置”的模块可以实现，但不维护了，新的API不支持。
可配置基站信息，诸如网络类型，MCC MNC LAC/TAC CID 之类的数据

### 必要性 / Necessity
加入基站定位，基本就能实现在任何APP中虚拟定位

**Comment by ZCShou** [comment]
没有 root 权限能模拟基站么？
