### ISSUE TITLE
[Question] Help 为什么定位软件会要电话权限？

### ISSUE THREAD

**Issue by jucat679** [ZCShou/GoGoGo#72]
### 问题描述 / Problem Description

如题

### 版本信息 / Version Info

- 影梭版本 / GoGoGo Version : 
- 系统版本 / OS Version :

**Comment by ZCShou** [comment]
因为软件的注册功能需要啊！你看看但凡带有注册功能的 APP 哪个不需要这个权限？APP 的介绍里写的很清楚，这个 APP 就是为了学习Android 编程，注册功能肯定得了解啊
