### ISSUE TITLE
钉钉打卡让拍照

### ISSUE THREAD

**Issue by qinoho** [ZCShou/GoGoGo#76]
<img width="326" alt="Snipaste_2024-01-31_18-31-56" src="https://github.com/ZCShou/GoGoGo/assets/105160735/faa912b8-b9da-47a5-ae07-7b42f855c360">

**Comment by ZCShou** [comment]
前段时间，钉钉增加了对于影梭的检测！

**Comment by kali7188** [comment]
> 前段时间，钉钉增加了对于影梭的检测！

牛修复吗

**Comment by kali7188** [comment]
可以修复吗

**Comment by kali7188** [comment]
钉钉检测是什么原理> 前段时间，钉钉增加了对于影梭的检测！

**Comment by ZCShou** [comment]
貌似是检测包名，换个包名就可以了！

**Comment by qinoho** [comment]
期待作者大大更新

**Comment by ZCShou** [comment]
> 期待作者大大更新

我更新没多大用处，很快就会再次被检测。最好的方式就是你们自己改一个自己专用的！
