### ISSUE TITLE
[Feature] 能否加入多地图选择的功能，比如支持 mapbox

### ISSUE THREAD

**Issue by qqizai** [ZCShou/GoGoGo#88]
### 描述 / Description

1、接入mapbox地图
2、加上导航模式，导航能设置速度，比如走路/踩单车/开车模式

### 必要性 / Necessity

1、主要是增加导航模式，能有一个走道路的选择，就不是直接两点之间的直走

**Comment by ZCShou** [comment]
欢迎来个 PR
