### ISSUE TITLE
在平板端无法使用

### ISSUE THREAD

**Issue by Saulwonderfulman** [ZCShou/GoGoGo#89]
### 缺陷描述 / Bug description
大部分平板并没有定位芯片,因此系统并没有给出开启定位的开关,猜测应该使用的WiFi定位,此时app安装完成后是无法进入的

### 版本信息 / Version Info

- 影梭版本 / GoGoGo Version : ReleaseV1.11.3
- 系统版本 / OS Version : 与系统版本无关

### 复现步骤 / Steps to Reproduce

1. 平板安装app打开即可复现

**Comment by ZCShou** [comment]
平板没有适配过，不能用很正常！
