### ISSUE TITLE
【警告】请认真阅读关于钉钉打卡的说明

### ISSUE THREAD

**Issue by ZCShou** [ZCShou/GoGoGo#95]
&emsp;&emsp;近期，很多人将影梭或者说类似的 APP 用于钉钉打卡，目前，钉钉已经针对网络上常见的定位 APP 进行了识别，没有任何有效手段可以保证 100% 不被识别。只要手机中安装了虚拟定位 APP（即使仅安装不使用） 进行打卡都会被警告，包括但不限于：
1. 提示拍照
![输入图片说明](https://foruda.gitee.com/images/1709014001704752299/159af3c7_500005.png "屏幕截图")
2. 提示人脸识别

&emsp;&emsp;在打卡过程中，无论出现何种提示，都会被钉钉记录到打卡后台。即使使用了拍照或者人脸识别进行确认打卡，依旧会被钉钉认为是无效的打卡记录，进而通知管理员处理。详见下图：
![输入图片说明](https://foruda.gitee.com/images/1709014451200443082/846c31b5_500005.png "屏幕截图")
 
**在此提醒，不要使用任何虚线定位工具进行打卡，否则请自行考虑后果！**
**在此提醒，不要使用任何虚线定位工具进行打卡，否则请自行考虑后果！**
**在此提醒，不要使用任何虚线定位工具进行打卡，否则请自行考虑后果！**

**Comment by gyqhsq521** [comment]
如果安装后，再卸载虚拟定位app，还会被钉钉记录至后台吗？

**Comment by gyqhsq521** [comment]
如果卸载虚拟定位app后，打卡还会被警告并被钉钉记录至后台吗？

**Comment by ZCShou** [comment]
> 如果卸载虚拟定位app后，打卡还会被警告并被钉钉记录至后台吗？

不会

**Comment by StationChnqoo** [comment]
就这么说吧，像钉钉这种的，虚拟定位改GPS是没用的，他的大数据IP库已经非常全面了，通过你的WIFI或者营运商所在的基站，就能确认你的位置，如果和手机GPS的位置有太大偏差，肯定会被记录无效，所以这个无解。我可以提供一种方法，搞一个备用手机放在公司，然后在家里通过公司VPN远程adb连接手机，直接adb操作手机打卡，谁也发现不了

**Comment by TheWaveLab** [comment]
> 就这么说吧，像钉钉这种的，虚拟定位改GPS是没用的，他的大数据IP库已经非常全面了，通过你的WIFI或者营运商所在的基站，就能确认你的位置，如果和手机GPS的位置有太大偏差，肯定会被记录无效，所以这个无解。我可以提供一种方法，搞一个备用手机放在公司，然后在家里通过公司VPN远程adb连接手机，直接adb操作手机打卡，谁也发现不了

只有靠物理手段才可绕过技术手段

**Comment by yuuouu** [comment]
> 就这么说吧，像钉钉这种的，虚拟定位改GPS是没用的，他的大数据IP库已经非常全面了，通过你的WIFI或者营运商所在的基站，就能确认你的位置，如果和手机GPS的位置有太大偏差，肯定会被记录无效，所以这个无解。我可以提供一种方法，搞一个备用手机放在公司，然后在家里通过公司VPN远程adb连接手机，直接adb操作手机打卡，谁也发现不了

不行的, adb打卡也会监控.会要求你断开adb连接再打卡..妈的

**Comment by javaController123** [comment]
> TeamViewer YYDS 多说无益

这个可以解决上面的问题吗？

**Comment by AnyLifeZLB** [comment]
> > TeamViewer YYDS 多说无益
> 
> 这个可以解决上面的问题吗？

可以，但是经常切换手机登录也会有记录吧

**Comment by ghostgeek** [comment]
> > 就这么说吧，像钉钉这种的，虚拟定位改GPS是没用的，他的大数据IP库已经非常全面了，通过你的WIFI或者营运商所在的基站，就能确认你的位置，如果和手机GPS的位置有太大偏差，肯定会被记录无效，所以这个无解。我可以提供一种方法，搞一个备用手机放在公司，然后在家里通过公司VPN远程adb连接手机，直接adb操作手机打卡，谁也发现不了
> 
> 不行的, adb打卡也会监控.会要求你断开adb连接再打卡..妈的

远程桌面也不行吗？

**Comment by javaController123** [comment]
> > > 就这么说吧，像钉钉这种的，虚拟定位改GPS是没用的，他的大数据IP库已经非常全面了，通过你的WIFI或者营运商所在的基站，就能确认你的位置，如果和手机GPS的位置有太大偏差，肯定会被记录无效，所以这个无解。我可以提供一种方法，搞一个备用手机放在公司，然后在家里通过公司VPN远程adb连接手机，直接adb操作手机打卡，谁也发现不了
> > 
> > 
> > 不行的, adb打卡也会监控.会要求你断开adb连接再打卡..妈的
> 
> 远程桌面也不行吗？

我已经有方法了，而且已经使用了好几个月了，有兴趣的话，可以加我qq，给你私发一下，不是商务--1425609123

**Comment by mostend** [comment]
从最早的虚拟定位, 虚拟机, 远程打卡,ADB, 目前都是可以被检测到的. 
我能想到的就只有自己搞个机械臂放在公司,到时间自动解锁打卡了

**Comment by javaController123** [comment]
> 从最早的虚拟定位, 虚拟机, 远程打卡,ADB, 目前都是可以被检测到的. 我能想到的就只有自己搞个机械臂放在公司,到时间自动解锁打卡了

不用的，有一款app就可以，我已经用这个实现一年满勤了。

**Comment by pigq** [comment]
> > 从最早的虚拟定位, 虚拟机, 远程打卡,ADB, 目前都是可以被检测到的. 我能想到的就只有自己搞个机械臂放在公司,到时间自动解锁打卡了
> 
> 不用的，有一款app就可以，我已经用这个实现一年满勤了。

啥APP！！

**Comment by 185Club** [comment]
你好，安装影梭的时候提示必须授权媒体访问权限，否则没法安装，想问下为什么必须访问媒体文件

**Comment by Chris61git** [comment]
> 就这么说吧，像钉钉这种的，虚拟定位改GPS是没用的，他的大数据IP库已经非常全面了，通过你的WIFI或者营运商所在的基站，就能确认你的位置，如果和手机GPS的位置有太大偏差，肯定会被记录无效，所以这个无解。我可以提供一种方法，搞一个备用手机放在公司，然后在家里通过公司VPN远程adb连接手机，直接adb操作手机打卡，谁也发现不了

那如果公司没有wifi网络怎么搞呢

**Comment by daka126** [comment]
新路行可以用，用以前卸载其他虚拟定位软件https://wwtw.lanzouq.com/xinluxing

**Comment by kingsunsun2012** [comment]
> 新路行可以用，用以前卸载其他虚拟定位软件https://wwtw.lanzouq.com/xinluxing

你好，有作者的更新链接吗

**Comment by bmtwdjxiang** [comment]
> 新路行可以用，用以前卸载其他虚拟定位软件https://wwtw.lanzouq.com/xinluxing

风险软件谨慎安装，第一个界面就是套路

**Comment by yangxiaoge** [comment]
唯一靠谱的方案就是，旧手机放到公司，然后配合tasker等自动化应用实现打卡。举个我的例子：我用的macrodroid软件，监听小号微信消息，大号给小号发送“打卡”，“查询”等指令，然后macrodroid软件监听后，去操作钉钉打卡，或者截屏，再通过微信把消息/图片发给大号即可。

**Comment by kingsunsun2012** [comment]
> 唯一靠谱的方案就是，旧手机放到公司，然后配合tasker等自动化应用实现打卡。举个我的例子：我用的macrodroid软件，监听小号微信消息，大号给小号发送“打卡”，“查询”等指令，然后macrodroid软件监听后，去操作钉钉打卡，或者截屏，再通过微信把消息/图片发给大号即可。

具体怎么实现的，能出一个操作流程吗

**Comment by lancewoo** [comment]
据说钉钉7.0.56检测不到，当然也不能用开源版包名，所以不要轻易升级。据说用闹铃就能唤醒打卡界面，剩下的自己脑补吧。

**Comment by daka126** [comment]
影梭顶配https://wwtw.lanzouq.com/yinsuodp
配合7.5.0版本丁丁
https://m.wandoujia.com/apps/6565746/history_v1106

**Comment by dq77** [comment]
到这里的都是懂点代码的吧，手机安装个Autojs就行，然后就剩coding了

**Comment by pigq** [comment]
> 到这里的都是懂点代码的吧，手机安装个Autojs就行，然后就剩coding了

这个咋用啊？ Autojs

**Comment by sumhaiqian** [comment]
影梭v2.0.0已经发布https://www.lanzouq.com/yinsuo2
